# Generated by Django 5.0.6 on 2024-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='work_hours',
            field=models.CharField(max_length=50),
        ),
    ]
