# Generated by Django 5.0.6 on 2024-06-15 19:33

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('medical_history', models.TextField()),
                ('current_conditions', models.TextField()),
                ('allergies', models.TextField()),
                ('medications', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('illness_type', models.CharField(max_length=100)),
                ('illness_name', models.CharField(max_length=100)),
                ('blood_pressure', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('addiction', models.BooleanField(blank=True, null=True)),
                ('addiction_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
