# Generated by Django 5.0.6 on 2024-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
